/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as ComparisonRouteImport } from './routes/comparison'
import { Route as ComplexityRouteImport } from './routes/complexity'
import { Route as EdgeCasesRouteImport } from './routes/edge-cases'
import { Route as LogRouteImport } from './routes/log'
import { Route as PeasRouteImport } from './routes/peas'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SimulationRouteImport } from './routes/simulation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexityRoute = ComplexityRouteImport.update({
  id: '/complexity',
  path: '/complexity',
  getParentRoute: () => rootRouteImport,
} as any)
const EdgeCasesRoute = EdgeCasesRouteImport.update({
  id: '/edge-cases',
  path: '/edge-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const PeasRoute = PeasRouteImport.update({
  id: '/peas',
  path: '/peas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/cases': typeof CasesRoute
  '/comparison': typeof ComparisonRoute
  '/complexity': typeof ComplexityRoute
  '/edge-cases': typeof EdgeCasesRoute
  '/log': typeof LogRoute
  '/peas': typeof PeasRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/simulation': typeof SimulationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/cases': typeof CasesRoute
  '/comparison': typeof ComparisonRoute
  '/complexity': typeof ComplexityRoute
  '/edge-cases': typeof EdgeCasesRoute
  '/log': typeof LogRoute
  '/peas': typeof PeasRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/simulation': typeof SimulationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/cases': typeof CasesRoute
  '/comparison': typeof ComparisonRoute
  '/complexity': typeof ComplexityRoute
  '/edge-cases': typeof EdgeCasesRoute
  '/log': typeof LogRoute
  '/peas': typeof PeasRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/simulation': typeof SimulationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/cases'
    | '/comparison'
    | '/complexity'
    | '/edge-cases'
    | '/log'
    | '/peas'
    | '/resources'
    | '/search'
    | '/simulation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/cases'
    | '/comparison'
    | '/complexity'
    | '/edge-cases'
    | '/log'
    | '/peas'
    | '/resources'
    | '/search'
    | '/simulation'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agents'
    | '/cases'
    | '/comparison'
    | '/complexity'
    | '/edge-cases'
    | '/log'
    | '/peas'
    | '/resources'
    | '/search'
    | '/simulation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  CasesRoute: typeof CasesRoute
  ComparisonRoute: typeof ComparisonRoute
  ComplexityRoute: typeof ComplexityRoute
  EdgeCasesRoute: typeof EdgeCasesRoute
  LogRoute: typeof LogRoute
  PeasRoute: typeof PeasRoute
  ResourcesRoute: typeof ResourcesRoute
  SearchRoute: typeof SearchRoute
  SimulationRoute: typeof SimulationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complexity': {
      id: '/complexity'
      path: '/complexity'
      fullPath: '/complexity'
      preLoaderRoute: typeof ComplexityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edge-cases': {
      id: '/edge-cases'
      path: '/edge-cases'
      fullPath: '/edge-cases'
      preLoaderRoute: typeof EdgeCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peas': {
      id: '/peas'
      path: '/peas'
      fullPath: '/peas'
      preLoaderRoute: typeof PeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  CasesRoute: CasesRoute,
  ComparisonRoute: ComparisonRoute,
  ComplexityRoute: ComplexityRoute,
  EdgeCasesRoute: EdgeCasesRoute,
  LogRoute: LogRoute,
  PeasRoute: PeasRoute,
  ResourcesRoute: ResourcesRoute,
  SearchRoute: SearchRoute,
  SimulationRoute: SimulationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
